In [7]:

import numpy as np
arr1 = np.arange(0, 15, 5)
print("using arange", arr1)

using arange [ 0  5 10]


In [12]:
arr2 = np.linspace(0,1,6)
print("Array using linspace:", arr2)


Array using linspace: [0.  0.2 0.4 0.6 0.8 1. ]


In [16]:
arr3 = np.arange(1,10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [18]:
data = np.array([[1,2,3], [4,5, 6]])

print("Original Data:\n", data)



Original Data:
 [[1 2 3]
 [4 5 6]]


In [19]:
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))


Sum of all elements: 21
Column-wise sum: [5 7 9]
Row-wise mean: [2. 5.]
Max value: 6


In [20]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))


Index of max value (flattened): 5
Min value: 1
Standard Deviation: 1.707825127659933


In [21]:
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)

Original Array: [3 1 7 2 9]


In [22]:
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])


Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]


In [28]:
A = np.array([[5,6], [7,8]])
B = np.array([10, 20])

print("Matrix A:\n", A)
print("Vector B:", B)

c=A+B
print("Addition:\n",c)


Matrix A:
 [[5 6]
 [7 8]]
Vector B: [10 20]
Addition:
 [[15 26]
 [17 28]]


In [29]:
nums = np.array([1, 2, 3, 4, 5])

# Create boolean mask for condition nums > 3
mask = nums > 3
print("Mask (nums > 3):", mask)


Mask (nums > 3): [False False False  True  True]


In [30]:
filtered = nums[mask]
print("Filtered values:", filtered)

# np.where: apply conditional logic
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [31]:
arr_orig = np.array([10, 20, 30])

# Creating a view (shares memory)
arr_view = arr_orig[:]
arr_view[0] = 99  # This change affects original
print("Original After View Change:", arr_orig)



Original After View Change: [99 20 30]


In [32]:
arr_copy = arr_orig.copy()
arr_copy[0] = 55  # This does NOT affect original
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)


Original After Copy Change: [99 20 30]
Copy: [55 20 30]


In [33]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Vertical stack (as rows)
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [34]:
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)

# Split an array into 3 sub-arrays
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)



Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [35]:

# Random integers from 0 to 100 in 3x3 matrix
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random values from standard normal distribution (mean=0, std=1)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)


Random Integers:
 [[39 62  9]
 [47 77 93]
 [38 93 58]]
Random Normal Distribution:
 [[ 0.54229924  0.75427054 -1.46988021  2.54322014]
 [-0.71339546 -1.03112428 -1.05667286 -0.13012876]]


In [36]:
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

Random Choices: [3 1 7 5 5]
Seeded Random Number: 0.3745401188473625


In [37]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])        # 10
print("Element at last index:", arr[-1])    # 60



Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60


In [38]:
# Slice elements [start:stop] (stop is exclusive)
print("Slice from index 1 to 4:", arr[1:4])  # [20, 30, 40]

# Slice with step
print("Every second element:", arr[::2])     # [10, 30, 50]

# Reverse array
print("Reversed array:", arr[::-1])          # [60, 50, ..., 10]


Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [39]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

print("Element at (1,2):", matrix[1, 2])  # 6


print("First row:", matrix[0, :])

print("Second column:", matrix[:, 1])

print("Top-left 2x2 block:\n", matrix[:2, :2])


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [41]:
arr = np.array([5, 10, 15, 20, 25, 30])

mask = arr > 15
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])

print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])


Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
