In [ ]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("Series:\n", s1_1)
print("\nNumPy Array:\n", np_array1_2)
print("\nDataFrame:\n", df1_3)


# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100).astype(float),
    'Quantity': np.random.randint(1, 11, 100).astype(float)
})

# Introduce NaN values
sales_nan_idx = np.random.choice(df_sales.index, size=5, replace=False)
quantity_nan_idx = np.random.choice(df_sales.index, size=3, replace=False)

df_sales.loc[sales_nan_idx, 'Sales'] = np.nan
df_sales.loc[quantity_nan_idx, 'Quantity'] = np.nan

print(df_sales.head())


# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1
df3_1 = df_sales[['Region', 'Sales']]

# 3.2
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]

# 3.4
monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]
val3_4 = df_sales.loc[monitor_index, 'Sales']

print("df3_1:\n", df3_1.head())
print("\ndf3_2:\n", df3_2.head())
print("\ndf3_3:\n", df3_3.head())
print("\nFirst Monitor Sales:", val3_4)


# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1
missing_counts4_1 = df_sales.isna().sum()

# 4.2
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())

# 4.3
df4_3_dropped = df_sales.dropna()

print("Missing Values:\n", missing_counts4_1)
print("\nFilled DataFrame:\n", df4_2_filled.head())
print("\nDropped NaN DataFrame:\n", df4_3_dropped.head())


# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# 5.2
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'],
                                    ascending=[True, False])

# 5.3
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

# 5.4
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("Data with Total Revenue:\n", df_sales.head())

print("\nSorted Data:\n", df5_2_sorted.head())

print("\nGrouped by Region:\n", df5_3_grouped_region)

print("\nAverage Sales by Product:\n", df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series:
 0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
 [[86 32 97 14]
 [10 34 75 89]
 [95 21 38 59]]

DataFrame:
     A   B   C   D
0  86  32  97  14
1  10  34  75  89
2  95  21  38  59

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01   East     Mouse  175.0       3.0
1 2023-01-02   East    Laptop  922.0       5.0
2 2023-01-03  North  Keyboard  187.0       9.0
3 2023-01-04   West  Keyboard  480.0       8.0
4 2023-01-05   West   Monitor  804.0       5.0

--- Task 3: Indexing and Slicing in DataFrames ---
df3_1:
   Region  Sales
0   East  175.0
1   East  922.0
2  North  187.0
3   West  480.0
4   West  804.0

df3_2:
          Date Region Product  Sales  Quantity
1  2023-01-02   East  Laptop  922.0 